<?xml version="1.0" encoding="utf-8"?><Database Name="multiShop" Class="MShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=multiShop;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="multiShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="shop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="navlink" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="id" OtherKey="category" Type="Product" />
      <Association Name="Shop_Category" Member="Shop1" ThisKey="shop" OtherKey="id" Type="Shop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Shop" Member="Shops">
    <Type Name="Shop">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Shop_Category" Member="Categories" ThisKey="id" OtherKey="shop" Type="Category" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="descrip" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fulldescrip" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="buylink" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Category_Product" Member="Category1" ThisKey="category" OtherKey="id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>